"""The tables, as PostgreSQL DDL.

Timestamps stay ISO-8601 TEXT ('2026-09-27T09:00:00Z'), as they were in
SQLite: they sort correctly as text, every query already compares them that
way, and `started_at::timestamptz` turns one into a real timestamp wherever
the dashboard needs date arithmetic.

Ids are identity columns generated BY DEFAULT, so the one-off SQLite importer
(app/db/import_sqlite.py) can keep a learner's existing ids and then move
the sequences past them.

There are no migrations here. A PostgreSQL database starts from this DDL;
older SQLite databases — including every shape the SQLite migrations used to
repair — come in once through the importer, which also backfills
sessions.kind for explain sessions written before that column existed.
"""

_SCHEMA = """\
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

CREATE TABLE IF NOT EXISTS user_profiles (
    id            BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name  TEXT    NOT NULL DEFAULT 'learner',
    target_lang   TEXT    NOT NULL,
    created_at    TEXT    NOT NULL,
    last_active   TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
    id            BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT  NOT NULL REFERENCES user_profiles(id),
    scenario_name TEXT    NOT NULL,
    language      TEXT    NOT NULL,
    mood          TEXT    NOT NULL,
    complication  TEXT,
    tasks_total   INTEGER NOT NULL,
    tasks_done    INTEGER NOT NULL DEFAULT 0,
    tasks_skipped INTEGER NOT NULL DEFAULT 0,
    started_at    TEXT    NOT NULL,
    finished_at   TEXT,
    -- 'scenario' (one of the 80 roleplay scenarios) or 'explain' (one of the
    -- explain-mode topics). Both park their display name in scenario_name;
    -- this column is what lets stats and the UI tell them apart.
    kind          TEXT    NOT NULL DEFAULT 'scenario'
);
CREATE INDEX IF NOT EXISTS idx_sess_user ON sessions(user_id);

CREATE TABLE IF NOT EXISTS task_logs (
    id              BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      BIGINT  NOT NULL REFERENCES sessions(id),
    scenario_name   TEXT    NOT NULL,
    user_id         BIGINT  NOT NULL REFERENCES user_profiles(id),
    task_index      INTEGER NOT NULL,
    goal            TEXT    NOT NULL,
    done_when       TEXT    NOT NULL,
    difficulty      TEXT    NOT NULL,
    phase           INTEGER NOT NULL,
    outcome         TEXT    NOT NULL,
    attempts_used   INTEGER NOT NULL,
    started_at      TEXT    NOT NULL,
    finished_at     TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tl_session ON task_logs(session_id);
CREATE INDEX IF NOT EXISTS idx_tl_user    ON task_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_tl_outcome ON task_logs(outcome);

CREATE TABLE IF NOT EXISTS vocab_log (
    id              BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT  NOT NULL REFERENCES user_profiles(id),
    language        TEXT    NOT NULL,
    word            TEXT    NOT NULL,
    explanation     TEXT    NOT NULL,
    scenario_name   TEXT    NOT NULL,
    times_taught    INTEGER NOT NULL DEFAULT 1,
    times_correct   INTEGER NOT NULL DEFAULT 0,
    first_taught_at TEXT    NOT NULL,
    last_seen_at    TEXT    NOT NULL,
    -- The word's embedding (pgvector), or NULL when it was logged without the
    -- optional embedder installed. Nullable on purpose: retrieval degrades to
    -- least-recently-seen rather than failing. Untyped (no dimension) so a
    -- different embedder does not need a schema change.
    embedding       public.vector
);
CREATE INDEX IF NOT EXISTS idx_vl_user_lang ON vocab_log(user_id, language);

-- One row per ❌/✅ correction bullet the coach produced, so a stats query can
-- answer "is this learner still making the same mistake?"
CREATE TABLE IF NOT EXISTS mistakes (
    id              BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT  NOT NULL REFERENCES user_profiles(id),
    language        TEXT    NOT NULL,
    session_id      BIGINT  NOT NULL REFERENCES sessions(id),
    scenario_name   TEXT    NOT NULL,
    quoted_text     TEXT    NOT NULL,
    correction      TEXT    NOT NULL,
    -- see _mistake_key: groups "two bottle"/"three bottle" and
    -- "I go yesterday"/"he go yesterday" into the same repeated class.
    normalized_key  TEXT    NOT NULL,
    created_at      TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_mistakes_user_lang_key ON mistakes(user_id, language, normalized_key);
"""

# Every table, in the order rows can be inserted (parents first) — the
# importer and the test cleanup both walk it.
TABLES = ('user_profiles', 'sessions', 'task_logs', 'vocab_log', 'mistakes')


def backfill_explain_kind(conn) -> None:
    """Mark as 'explain' the sessions whose scenario_name is an explain topic.

    Explain mode shipped before sessions.kind did, and those sessions were
    written with the topic title in scenario_name — 4 of them in the author's
    own database. Matching on name is safe: a scenario name is a place
    ("Coffee Shop"), a topic title a sentence, and anything the scenario
    catalogue claims is excluded. Called by the SQLite importer.
    """
    from ..explain import load_topics
    from ..scenarios.builtins import load_scenarios
    scenario_names = {sc.name for sc in load_scenarios()}
    titles = {t.title(lang) for t in load_topics()
              for lang in ('English', 'Japanese')} - scenario_names
    for title in titles:
        conn.execute("UPDATE sessions SET kind = 'explain' WHERE scenario_name = %s", (title,))
    conn.commit()
