// The few visible lines that are not in app/i18n.py: the landing page's
// loading screen, connection notices, toasts and the summary sentence. They
// used to be inline `lang === 'Japanese' ? … : …` ternaries scattered through
// the page; one table per language keeps them in one place. Every label that
// IS in i18n.py comes from /api/strings instead (see useStrings in Practice).
import type { Language } from './types'

const plural = (n: number, word: string) => `${n} ${word}${n === 1 ? '' : 's'}`

const EN = {
  htmlLang: 'en',
  boot: {
    preparing: ['Preparing your scenario', 'Getting your tasks ready…'],
    greeting: ['Setting the scene', 'Getting your conversation partner ready — this can take a moment.'],
  } as Record<string, [string, string]>,
  stage: { judging: 'Checking your answer…', replying: 'Writing a reply…', coaching: 'Reviewing your grammar…' } as Record<string, string>,
  thinking: 'thinking…',
  reconnecting: 'Connection lost — reconnecting…',
  ended: 'This session has ended. Reload the page to start a new one.',
  resumed: 'Welcome back — your session has been restored.',
  finishFirst: 'Retype the correction first.',
  skipped: 'Task skipped',
  taskDone: '✓ Task complete',
  newWord: (w: string) => `📖 New word: ${w}`,
  couldntSend: "Couldn't send that",
  natural: '✓ Sounds natural',
  levelUp: 'More natural',
  left: (n: number) => `${n} left`,
  doneLine: (done: number, missed: number) => `${plural(done, 'task')} completed · ${missed} skipped or missed`,
  rank: (r: string) => r.charAt(0).toUpperCase() + r.slice(1),
  playsTo: (n: number, rank: string) => `Play ${n} more ${n > 1 ? 'times' : 'time'} to reach ${rank}`,
  pctTo: (p: number, rank: string) => `Raise your best score by ${p} points to reach ${rank}`,
  wordsDue: (n: number) => `${n} word${n > 1 ? 's' : ''} waiting to be practiced`,
  sep: ' · ',
  kpi: { sessions: 'Sessions', tasks: 'Tasks', completion: 'Completion', words: 'Words' },
  fixes: 'Corrections this session',
  margin: 'Margin notes',
  rewrite: 'Write it again, right:',
  hanamaru: 'Right! 花丸',
  today: {
    greeting: (hour: number): string => (hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening'),
    date: (d: Date) => d.toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short' }),
    nav: { today: "Today's page", browse: 'Scenarios', progress: 'Progress', dashboard: 'Dashboard' },
    goalWaiting: "Today's 花丸 is waiting",
    goalHint: 'Finish one page to earn it.',
    goalDone: "Today's page is done — 花丸",
    streak: (n: number) => `${n}-day streak`,
    upNext: 'UP NEXT · REDO',
    redoTitle: (n: number) => (n === 1 ? 'One red mark to make right' : `${n} red marks to make right`),
    redoNote: 'A short chat with a friend where these come up again.',
    redoStart: 'Start the redo',
    freshKicker: 'UP NEXT',
    freshTitle: 'Start a conversation',
    freshNote: 'A scenario is picked for you, and the coach corrects you as you go.',
    freshStart: 'Start',
    orFresh: 'Or start a fresh page',
    conversation: ['Conversation', 'A scenario picked for you, ten tasks to talk your way through.'],
    explain: ['Explain', 'Talk longer: teach a listener a topic and answer their questions.'],
    browse: ['Browse scenarios', 'All 80, from a coffee shop to a customs hearing.'],
    recent: 'Latest red marks',
  },
  page: {
    title: 'Page complete',
    closed: 'Page closed',
    fixedLine: (n: number) => `${n} red mark${n === 1 ? '' : 's'} fixed — 花丸 ×${n}`,
    best: 'BEST LINE TODAY',
    bestWhy: 'Not one red mark on it.',
    fixedHead: 'What you fixed',
    comeBack: "These come back in a redo on Today's page until they stick.",
    words: 'New words',
    home: "Today's page",
    retyped: 'Retyped right',
    notYet: 'not retyped yet',
  },
}

type Copy = typeof EN

const JA: Copy = {
  htmlLang: 'ja',
  boot: {
    preparing: ['シナリオを準備しています', '目標を翻訳しています…'],
    greeting: ['シナリオを用意しています', 'モデルの起動中です。最初だけ時間がかかります。'],
  },
  stage: { judging: '回答を確認しています…', replying: '返事を書いています…', coaching: '文法を見ています…' },
  thinking: '考えています…',
  reconnecting: '接続が切れました。再接続しています…',
  ended: 'セッションが終了しました。ページを再読み込みしてください。',
  resumed: 'セッションを再開しました。',
  finishFirst: '先に訂正を入力してください。',
  skipped: 'タスクをスキップしました',
  taskDone: '✓ タスク達成！',
  newWord: (w) => `📖 新しい単語: ${w}`,
  couldntSend: '送信できませんでした',
  natural: '✓ 自然です',
  levelUp: 'レベルアップ',
  left: (n) => `あと${n}件`,
  doneLine: (done, missed) => `達成 ${done}件・未達成 ${missed}件`,
  rank: (r) => ({ experienced: '経験者', mastered: 'マスター' } as Record<string, string>)[r] ?? r,
  playsTo: (n, rank) => `あと${n}回プレイで「${rank}」に`,
  pctTo: (p, rank) => `ベストスコアをあと${p}%上げると「${rank}」に`,
  wordsDue: (n) => `復習待ちの単語 ${n}語`,
  sep: ' ・ ',
  kpi: { sessions: 'セッション', tasks: 'タスク', completion: '達成率', words: '単語' },
  fixes: '今回の訂正',
  margin: '赤ペンメモ',
  rewrite: 'もう一度、正しく書こう：',
  hanamaru: '正解！花丸',
  today: {
    greeting: (hour) => (hour < 11 ? 'おはようございます' : hour < 18 ? 'こんにちは' : 'こんばんは'),
    date: (d) => d.toLocaleDateString('ja-JP', { month: 'long', day: 'numeric', weekday: 'short' }),
    nav: { today: '今日のページ', browse: 'シナリオ', progress: '進み具合', dashboard: 'ダッシュボード' },
    goalWaiting: '今日の花丸はまだです',
    goalHint: '1ページ終えると、もらえます。',
    goalDone: '今日のページ、完了！花丸',
    streak: (n) => `${n}日連続`,
    upNext: '次は・やり直し',
    redoTitle: (n) => `直す赤ペンが${n}つ`,
    redoNote: 'これがまた出てくる、友達との短いおしゃべりです。',
    redoStart: 'やり直しを始める',
    freshKicker: '次は',
    freshTitle: '会話をはじめる',
    freshNote: 'シナリオはおまかせ。話しながら、コーチが直してくれます。',
    freshStart: 'はじめる',
    orFresh: '新しいページを始める',
    conversation: ['会話', 'おまかせのシナリオで、10のタスクを話してこなす。'],
    explain: ['説明する', '長めに話す練習：相手にテーマを説明して、質問に答える。'],
    browse: ['シナリオを選ぶ', 'カフェから税関まで、全80シナリオ。'],
    recent: '最近の赤ペン',
  },
  page: {
    title: 'ページ完了',
    closed: 'ページを閉じました',
    fixedLine: (n) => `赤ペンを${n}つ直した — 花丸 ×${n}`,
    best: '今日のいちばん',
    bestWhy: '赤ペンがひとつもない一文。',
    fixedHead: '直したところ',
    comeBack: '身につくまで、今日のページの「やり直し」でまた出てきます。',
    words: '新しい単語',
    home: '今日のページ',
    retyped: '正しく書き直した',
    notYet: 'まだ書き直していない',
  },
}

export const copyFor = (lang: Language): Copy => (lang === 'Japanese' ? JA : EN)
