import sys

sys.path.insert(0, '.')

sc3_code = '''scenario_3_tasks = [
    Task("Ask for painkillers", "You need to communicate this. Say you have a headache and need medicine.", "Learner asked for painkillers or headache medicine.", phase=1, scene_hint="Rows of neatly labeled medicine bottles line the white shelving behind the pharmacy counter."),
    Task("Ask about side effects", "You need information. Ask if the medicine makes you sleepy.", "Learner asked about side effects or drowsiness.", reactive=True),
    Task("Use the word 'prescription'", "A prescription is a formal authorization issued by a licensed medical practitioner. Present your prescription to the pharmacist.", "Learner used the word 'prescription'.", phase=1),
    Task("Ask for a thermometer", "You need information. Ask where the thermometers are.", "Learner asked to buy a thermometer.", scene_hint="An electronic digital wall thermometer displays the current room temperature in bright red numbers."),
    Task("Say you have a sore throat", "This is important context. Mention your throat hurts.", "Learner mentioned a sore throat."),
    Task("Ask for cough drops", "You need information. Ask for lozenges or cough drops.", "Learner asked for cough drops."),
    Task("Ask how often to take the medicine", "You need information. Ask about the dosage schedule.", "Learner asked how many times a day to take it."),
    Task("Use the word 'allergy'", "An allergy is an immune system hypersensitivity to a specific substance. Inform the pharmacist about your penicillin allergy.", "Learner used the word 'allergy'."),
    Task("Ask for band-aids/plasters", "You need information. Ask for bandages.", "Learner asked for band-aids or plasters.", scene_hint="Boxes of adhesive bandages in various sizes are stacked in a clear plastic acrylic bin."),
    Task("Ask for eye drops", "You need to communicate this. Say your eyes are dry.", "Learner asked for eye drops."),
    Task("Say you have a fever", "This is important context. Mention you have a high temperature.", "Learner mentioned having a fever."),
    Task("Ask for cold medicine", "You need information. Ask for medicine for a cold.", "Learner asked for cold medicine."),
    Task("Use the word 'symptoms'", "Symptoms are physical or mental indicators of a medical condition. Describe your symptoms to help the pharmacist recommend treatment.", "Learner used the word 'symptoms'."),
    Task("Ask if the medicine needs to be taken with food", "You need information. Ask if you should eat before taking it.", "Learner asked if it should be taken with food.", reactive=True),
    Task("Ask for a smaller pack", "You need to communicate this. Say the box is too big.", "Learner asked for a smaller quantity."),
    Task("Ask for generic brand", "You need information. Ask for a cheaper generic version.", "Learner asked for generic medicine."),
    Task("Use the word 'efficacy'", "Efficacy refers to the capacity or power to produce a desired therapeutic effect. Inquire about the efficacy of the recommended ointment.", "Learner used the word 'efficacy'."),
    Task("Ask for sunscreen", "You need information. Ask for sun protection.", "Learner asked for sunscreen.", scene_hint="Tubes of sunscreen and after-sun lotion fill a revolving floor display stand."),
    Task("Ask for insect repellent", "You need information. Ask for bug spray.", "Learner asked for insect repellent."),
    Task("Ask if you need to keep it in the fridge", "You need information. Ask about storage instructions.", "Learner asked if it needs refrigeration.", reactive=True),
    Task("Say you lost your prescription", "You need to clarify the situation. Explain you lost the paper.", "Learner said they lost their prescription.", difficulty="advanced"),
    Task("Ask to speak to the pharmacist", "You need something. Request the main pharmacist.", "Learner asked to speak to the pharmacist.", phase=1),
    Task("Ask for a refill", "You need information. Ask to refill an old prescription.", "Learner asked for a prescription refill.", phase=1),
    Task("Use the word 'adverse'", "Adverse refers to harmful, unintended, or unfavorable medical reactions. Ask about potential adverse effects of the medication.", "Learner used the word 'adverse'."),
    Task("Ask for vitamins", "You need information. Ask for vitamin C.", "Learner asked for vitamins."),
    Task("Ask for a covid test", "You need information. Ask for a rapid test.", "Learner asked for a covid/antigen test.", scene_hint="Rapid diagnostic antigen test kits in sealed white foil packs sit near the cash register."),
    Task("Say your stomach hurts", "This is important context. Mention a stomachache.", "Learner mentioned stomach pain."),
    Task("Ask for antacids", "You need information. Ask for digestion medicine.", "Learner asked for stomach medicine/antacids.", reactive=True),
    Task("Ask what the expiration date is", "You need information. Ask when it expires.", "Learner asked about the expiration date.", phase=3),
    Task("Ask if they accept your health insurance", "You need information. Ask if they take your insurance.", "Learner asked if their insurance is accepted."),
    Task("Say you need it urgently", "This is important context. Mention it is an emergency.", "Learner said they need it right away."),
    Task("Ask for a paper bag", "You need information. Ask for a bag.", "Learner asked for a paper bag.", phase=3),
    Task("Ask if there is a generic alternative", "You need information. Ask for a generic version.", "Learner asked for a generic version."),
    Task("Say you have a rash", "This is important context. Mention a skin rash.", "Learner mentioned a rash."),
    Task("Ask for ointment", "You need information. Ask for skin cream/ointment.", "Learner asked for ointment.", scene_hint="Tubes of soothing hydrocortisone ointment and skin creams are arranged on the bottom shelf."),
    Task("Ask if the medicine is safe during pregnancy", "You need information. Ask if it's safe for pregnant women.", "Learner asked if it is safe during pregnancy."),
    Task("Ask for baby formula", "You need information. Ask where baby formula is.", "Learner asked for baby formula."),
    Task("Ask how long it will take to prepare", "You need information. Ask about wait time.", "Learner asked how long to prepare the prescription.", reactive=True),
    Task("Say you will come back later", "You need to communicate this. Say you'll return in an hour.", "Learner said they will come back.", phase=3),
    Task("Ask for the receipt for insurance", "You need information. Ask for a detailed receipt.", "Learner asked for an insurance receipt.", phase=3),
    Task("Ask about the recommended dosage", "You need information. Ask what the correct dosage is.", "Learner asked about the recommended dosage."),
    Task("Ask for liquid medicine instead of pills", "You need to communicate this. Say you can't swallow pills.", "Learner asked for liquid medicine.", difficulty="advanced"),
    Task("Say it's for a child", "You have a specific preference. Specify the patient is a child.", "Learner said the medicine is for a child."),
    Task("Ask what age it is suitable for", "You need information. Ask the minimum age.", "Learner asked about age restrictions."),
    Task("Ask for a measuring cup", "You need information. Ask for a cup to measure liquid.", "Learner asked for a measuring cup or spoon.", reactive=True),
    Task("Ask how quickly the medicine takes effect", "You need information. Ask how fast it starts working.", "Learner asked how quickly the medicine works."),
    Task("Ask for hand sanitizer", "You need information. Ask for hand gel.", "Learner asked for hand sanitizer.", scene_hint="Pump bottles of clear hand sanitizer sit beside a stack of blue surgical face masks on the counter."),
    Task("Ask for a medical mask", "You need information. Ask for face masks.", "Learner asked for a mask."),
    Task("Say thank you and leave", "It's time to go. End the conversation politely.", "Learner thanked the pharmacist and left.", phase=3),
    Task("Describe how you're feeling, then narrow it down", "Start general, then get specific when they ask.", "Learner described a general complaint AND added a specific detail such as when it started or what makes it worse.", difficulty="advanced"),
    Task("Ask what happens if it doesn't agree with you", "Find out what to watch for and what to do about it.", "Learner asked about possible effects AND asked what action to take if they occur.", difficulty="advanced", reactive=True),
    Task("Say you've already tried something and it didn't help", "Tell them what you tried and what happened, then ask what else there is.", "Learner named a previous attempt AND described the outcome AND asked for an alternative.", difficulty="advanced", reactive=True),
    Task("Check the instructions by saying them back", "Repeat what they told you in your own words to confirm you've got it.", "Learner restated the instructions in their own words AND asked for confirmation.", difficulty="advanced", reactive=True),
    Task("Explain a restriction and ask what fits", "There's something you can't take. Explain it and ask what would work instead.", "Learner stated a constraint AND asked for a suitable alternative.", difficulty="advanced", reactive=True, scene_hint="The pharmacist places two different pill bottles side-by-side on the counter tray for comparison."),
    Task("Turn down what they suggest and ask for something else", "Decline politely, say why, and ask what else they'd recommend.", "Learner declined AND gave a reason AND asked for another option.", difficulty="advanced", reactive=True),
    Task("Raise a drug-interaction concern", "You're already taking something else. Ask if the new medication is safe to combine with it, and say what you're currently taking.", "Learner named what they're currently taking AND asked specifically about interaction risk.", difficulty="advanced"),
    Task("Negotiate around an insurance issue", "Your insurance doesn't seem to cover this. Explain the issue and ask what your options are.", "Learner explained the coverage problem AND asked for alternative options.", difficulty="advanced", phase=3),
    Task("Push for a second opinion diplomatically", "You're not fully convinced by the first recommendation. Say so tactfully and ask for more explanation or an alternative.", "Learner expressed polite skepticism about the recommendation AND asked for further explanation or an alternative.", difficulty="advanced", reactive=True),
    Task("Explain an urgent substitution need", "What you need is out of stock. Explain why you need it urgently and ask for the closest substitute.", "Learner explained the urgency AND asked for a specific substitute.", difficulty="advanced"),
    Task("Weigh long-term side effects out loud", "Ask about long-term risks of a treatment, then reason out loud about whether the benefit is worth it.", "Learner asked about long-term effects AND weighed the trade-off aloud AND asked for the pharmacist's opinion.", difficulty="advanced"),
    Task("Request documentation for a specific purpose", "You need proof of purchase or a note for insurance or work. Explain exactly why, and ask what they can provide.", "Learner explained the specific reason documentation is needed AND asked what the pharmacist can provide.", difficulty="advanced", phase=3),
    Task("Raise a dosage concern for a special circumstance", "Explain a circumstance that might affect dosage (age, pregnancy, an existing condition) and ask them to confirm it's safe.", "Learner disclosed the relevant circumstance AND asked for confirmation of safety or an adjusted dosage.", difficulty="advanced"),
    Task("Contest a mismatch between the label and what you were told", "Something on the label seems to contradict what you were told earlier. Point out the discrepancy and ask them to clarify.", "Learner identified the specific discrepancy AND asked for clarification.", difficulty="advanced", reactive=True, scene_hint="A printed prescription label on the amber vial shows instructions in black text."),
    Task("Negotiate switching to a cheaper alternative", "Ask if there's a generic or cheaper version, and ask how it compares in effectiveness.", "Learner asked about a cheaper alternative AND asked how it compares in effectiveness.", difficulty="advanced", phase=3),
    Task("Explain a past bad reaction and ask for reassurance", "You had a bad experience with something similar before. Explain what happened and ask if this one is different.", "Learner described a past negative reaction AND asked whether the current option carries the same risk.", difficulty="advanced"),
    Task("Ask about allergy medicine", "Pharmacists often recommend specific allergy medicines to customers. Try asking the pharmacist about common allergy medicines.", "Learner asks the pharmacist about allergy medicines", phase=1, scene_hint="Shelves of antihistamines and nasal sprays line the counter display."),
    Task("Inquire about pain relief options", "Pharmacists can suggest various pain relief options based on the type of pain. Ask the pharmacist about pain relief treatments.", "Learner inquires about pain relief options", phase=1, scene_hint="A digital pharmacy monitor shows available over-the-counter pain relievers."),
    Task("Discuss medication interactions", "Sometimes, customers are unsure about interactions between their current medications and any new ones. Ask the pharmacist about potential interactions.", "Learner discusses medication interactions with the pharmacist", difficulty="advanced", phase=3, reactive=True, scene_hint="The pharmacist opens a thick medical reference binder on the glass counter."),
    Task("Request an explanation of side effects", "You have a new prescription and want to make sure you understand the possible side effects before taking the medication.", "Learner asks the pharmacist about the potential side effects of the new prescription.", difficulty="advanced", reactive=True, scene_hint="The pharmacist holds up an amber pill bottle with a yellow warning sticker.")
]'''

with open('scratch/sc3_fixed.py', 'w') as f:
    f.write(sc3_code)

print("Wrote sc3_fixed.py")
