import sys
import re

sys.path.insert(0, '.')

# We will generate the Python code for scenario_0_tasks cleanly.
sc0_code = '''scenario_0_tasks = [
    Task("Ask for a table for two", "You need a table. Ask for a table for two people.", "Learner asked for a table for two.", phase=1),
    Task("Ask for the menu", "You need to see the food options. Ask for a menu.", "Learner asked for a menu.", phase=1),
    Task("Order a glass of red wine", "You want to buy this. Order red wine.", "Learner ordered red wine."),
    Task("Ask for a recommendation", "You need help choosing. Ask what they recommend.", "Learner asked for a recommendation."),
    Task("Order the steak medium-rare", "You want to buy this. Order steak and specify medium-rare.", "Learner ordered a medium-rare steak."),
    Task("Say you are allergic to seafood", "Explain your severe seafood allergy and confirm that kitchen staff will use separate preparation surfaces.", "Learner mentioned a seafood allergy AND asked for cross-contamination precautions.", difficulty="advanced"),
    Task("Ask what the soup of the day is", "You need information. Ask about today's soup.", "Learner asked about the soup of the day."),
    Task("Ask if they have any vegetarian options", "You need information. Ask about vegetarian food.", "Learner asked for vegetarian options."),
    Task("Complain that the food is cold", "You need to communicate this. Say your food is cold.", "Learner complained about cold food.", difficulty="advanced", reactive=True),
    Task("Ask for some salt and pepper", "You need something. Ask for seasonings.", "Learner asked for salt and pepper."),
    Task("Say the steak is overcooked", "You have a complaint. Say the meat is cooked too much.", "Learner complained the steak is overcooked.", difficulty="advanced", reactive=True),
    Task("Ask for a replacement dish", "You need a solution. Ask them to replace the food.", "Learner asked for a replacement.", difficulty="advanced", reactive=True),
    Task("Ask for tap water instead of sparkling", "You have a specific preference. Ask for still/tap water.", "Learner asked for tap water."),
    Task("Ask for a new fork", "You dropped it or it's dirty. Ask for a clean fork.", "Learner asked for a fork."),
    Task("Say the music is too loud", "You have a delicate request. Politely ask them to turn down the music.", "Learner complained about loud music.", difficulty="advanced", scene_hint="Classical violin music echoes loudly from speakers mounted directly above your table."),
    Task("Order a dessert", "You want to buy this. Ask to see the dessert menu or order dessert.", "Learner ordered or asked for dessert.", phase=3),
    Task("Ask if they serve coffee", "You need information. Ask if you can order coffee.", "Learner asked about coffee.", phase=3),
    Task("Ask for the bill", "You are finished. Ask for the check/bill.", "Learner asked for the bill.", phase=3),
    Task("Ask if you can split the bill", "You need information. Ask to pay separately.", "Learner asked to split the bill.", difficulty="advanced", phase=3),
    Task("Leave a tip", "You need to communicate this. Say you are leaving a tip.", "Learner explicitly mentioned leaving a tip.", phase=3),
    Task("Use the word 'sommelier'", "A sommelier is a trained wine professional who manages wine pairings and cellars. Request to consult with the sommelier.", "Learner used the word 'sommelier'."),
    Task("Use the word 'appetizer'", "An appetizer is a small dish served prior to the main course. Inquire about the chef's featured appetizers.", "Learner used the word 'appetizer'."),
    Task("Use the word 'napkin'", "A napkin is a fabric square used to protect clothing and wipe hands. Request an extra cloth napkin from the server.", "Learner used the word 'napkin'."),
    Task("Say you want to cancel an order", "You changed your mind. Cancel a dish you ordered.", "Learner cancelled an order.", difficulty="advanced", reactive=True),
    Task("Ask if the dish is spicy", "You need information. Ask about the spice level.", "Learner asked if the food is spicy."),
    Task("Ask where the restroom is", "You need information. Ask for the restroom/toilet.", "Learner asked for the restroom location."),
    Task("Compliment the chef", "You enjoyed the meal. Tell the waiter to pass your compliments to the chef.", "Learner complimented the chef.", difficulty="advanced", phase=3),
    Task("Ask what time the kitchen closes", "You need information. Ask about kitchen closing time.", "Learner asked when the kitchen closes.", phase=3),
    Task("Order a sparkling water", "You want to buy this. Order sparkling water.", "Learner ordered sparkling water."),
    Task("Ask if they take Apple Pay", "You need information. Ask about payment methods.", "Learner asked about Apple Pay.", phase=3),
    Task("Say your food hasn't arrived yet", "You are waiting. Point out the delay.", "Learner complained about a delay.", difficulty="advanced", reactive=True),
    Task("Ask for a high chair for a baby", "You need this for a child. Ask for a high chair.", "Learner asked for a high chair."),
    Task("Ask for some extra bread", "You want more. Ask for a bread refill.", "Learner asked for extra bread."),
    Task("Say the glass is dirty", "You have a complaint. Point out a dirty glass.", "Learner complained about a dirty glass.", difficulty="advanced", reactive=True),
    Task("Order a salad on the side", "You want to buy this. Add a side salad to your order.", "Learner ordered a side salad."),
    Task("Ask if the dressing is on the side", "You have a preference. Ask for dressing separately.", "Learner asked for dressing on the side."),
    Task("Use the word 'reservation'", "A reservation is an arrangement securing a dining table in advance. Inform the host that you have a reservation under your name.", "Learner used the word 'reservation'."),
    Task("Ask for a quiet table", "You have a preference. Request to sit somewhere quiet.", "Learner asked for a quiet table.", phase=1),
    Task("Ask if they have a kids menu", "You need information. Ask about food for children.", "Learner asked for a kids menu."),
    Task("Say you are in a hurry", "This is important context. Tell them you need quick service.", "Learner mentioned being in a hurry.", difficulty="advanced"),
    Task("Inquire about dietary restrictions", "Ask the waiter about modifications to accommodate your needs.", "Learner asked for a dish modification due to dietary restrictions.", phase=1),
    Task("Request an itemized bill", "Use proper language to request the final invoice.", "Learner asked to receive the itemized bill for the table.", phase=3, scene_hint="A waiter in a black vest is clearing empty starter plates from the table."),
    Task("Express dissatisfaction with the meal", "Clearly state your issue while maintaining respect.", "Learner expressed dissatisfaction with how the food was prepared and asked for an adjustment.", difficulty="advanced"),
    Task("Ask for a menu in another language", "Request the menu in a language you're comfortable with.", "Learner asked for a menu in a specific or alternate language.", difficulty="advanced", phase=1, scene_hint="The waiter holds two leather-bound menus open at eye level."),
    Task("Negotiate a special request", "Politely ask for a modification to the dish or service.", "Learner requested a dessert modification or allergen-free option.", difficulty="advanced"),
    Task("Inquire about the restaurant's history", "Ask the waiter about the establishment's background.", "Learner asked about the history or background of the restaurant.", difficulty="advanced", phase=1),
    Task("Request a dessert menu", "Ask the waiter for options on the dessert course.", "Learner requested to see the dessert menu.", phase=3, scene_hint="The waiter clears the main course plates with a quiet clatter of silverware."),
    Task("Order a cocktail", "Specify the drink you want and confirm the order.", "Learner ordered a specific cocktail (e.g. martini).", phase=1),
    Task("Complain about the noise", "Politely mention the noise level and ask for a solution.", "Learner complained about excessive noise level and requested a quieter setting or lower volume.", reactive=True),
    Task("Order a vegetarian dish", "Specify your dietary preference and ask for options.", "Learner ordered a vegetarian dish."),
    Task("Request a refill of water", "Politely ask for a refill of your drink.", "Learner asked for a refill or another glass of water.", phase=1, reactive=True),
    Task("Complain about the food temperature", "Politely mention that the dish is too hot or cold.", "Learner complained about food temperature and requested it to be reheated or replaced.", reactive=True),
    Task("Request a private booth", "Ask the waiter to find a private seating area.", "Learner requested a private booth or quiet table.", difficulty="advanced", phase=1),
    Task("Request a menu change for a food allergy", "Ask if the restaurant can accommodate allergies or special diets.", "Learner requested a menu adjustment for a food allergy", difficulty="advanced", reactive=True),
    Task("Ask to see the menu again", "Politely request the menu from the waiter.", "Learner requested to see the menu.", phase=1, scene_hint="The waiter stands by the sideboard holding a polished silver water pitcher."),
    Task("Ask to be moved away from the noise", "Politely mention the noise level in the restaurant.", "Learner asked to reduce noise level or change seating.", phase=1, reactive=True),
    Task("Ask for the check", "Request the bill after completing your meal.", "Learner requested the check or payment tab from the server.", phase=3, scene_hint="The waiter places a leather bill booklet face-down beside your water glass."),
    Task("Request a refill", "Ask for more water or wine during the meal.", "Learner requested a drink refill.", scene_hint="An empty water glass with melted ice sits at the edge of your place setting."),
    Task("Compliment the food", "Express satisfaction with the meal quality.", "Learner complimented the food or meal quality.", phase=3, scene_hint="The waiter sets down a covered silver dish emitting a rich savory aroma."),
    Task("Ask for a specific dish recommendation", "Seek advice from the waiter on the best dish.", "Learner asked for a dish recommendation."),
    Task("Inquire about the chef", "Ask the waiter about the chef's background.", "Learner asked about the chef's background or culinary experience.", difficulty="advanced", phase=3),
    Task("Ask about special dietary needs", "Confirm if the restaurant can accommodate allergies.", "Learner asked about allergen-free or nut-free options."),
    Task("Offer a tip for good service", "Add a gratuity for the waiter's service.", "Learner offered or mentioned leaving a tip for service.", phase=3),
    Task("Order a drink", "Choose a beverage and inform the waiter of your selection.", "Learner ordered a beverage or glass of wine.", phase=1, scene_hint="A waiter carrying a heavy brass tray laden with cocktail glasses approaches."),
    Task("Complain about the noise level", "Politely mention that the restaurant is too noisy.", "Learner asked for a quieter seating location due to noise.", difficulty="advanced", reactive=True, scene_hint="Cutlery clatters loudly from a busy busser station directly behind your chair."),
    Task("Ask about gluten-free menu options", "Ask the waiter about options for allergies or preferences.", "Learner inquired about gluten-free or special dietary options.", difficulty="advanced", reactive=True, scene_hint="The waiter is quietly reading out daily specials to guests at the next table."),
    Task("Request a wine recommendation", "Ask the waiter about wine pairings for your meal.", "Learner asks the waiter for a wine pairing recommendation.", reactive=True, scene_hint="The waiter holds out an open leather wine list showing reserve vintages."),
    Task("Request a modification to the order", "If you need to adjust your order, politely ask the waiter for changes.", "Learner specifies the desired cooking level for their steak.", difficulty="advanced", reactive=True),
    Task("Use the word 'ambiance'", "Ambiance refers to the atmosphere, mood, and character of a dining environment. Comment on the restaurant's elegant ambiance.", "Learner used the word 'ambiance'.", scene_hint="Soft candlelight glimmers on crystal stemware across the dining room.")
]'''

with open('scratch/sc0_fixed.py', 'w') as f:
    f.write(sc0_code)

print("Wrote sc0_fixed.py")
