scenario_2_tasks = [
    Task("Order a regular black coffee", "You want to buy this. Order a black coffee.", "Learner ordered a black coffee.", phase=1, scene_hint="The espresso machine hums softly, releasing a rich aroma of freshly ground coffee."),
    Task("Ask for the price", "You need information. Ask how much it costs.", "Learner asked about the price or total."),
    Task("Ask for a medium size", "You have a specific preference. Specify that you want a medium.", "Learner specified medium size."),
    Task("Ask what the most popular drink is", "You need information. Ask for a recommendation/popular item.", "Learner asked what is popular.", phase=1),
    Task("Say you want it to go (takeaway)", "You must inform them. Tell them it's for takeout.", "Learner said to go or takeaway.", scene_hint="Paper cups and cardboard sleeves are stacked high on the counter beside the register."),
    Task("Ask for extra napkins", "You need information. Ask for some napkins.", "Learner asked for napkins."),
    Task("Use the word 'roast'", "Roast refers to the process and degree of heating coffee beans to develop flavor and aroma. Inquire whether a dark roast option is available.", "Learner used the word 'roast'."),
    Task("Pay with a credit card", "You need to communicate this. Say you'll pay by card.", "Learner mentioned paying with a card.", phase=3),
    Task("Ask where the restroom is", "You need information. Ask for the restroom/toilet.", "Learner asked for the restroom location."),
    Task("Say you changed your mind about the order", "You need to communicate this. Say you want to change your order.", "Learner expressed a change of mind.", reactive=True),
    Task("Ask if they have any vegan pastries", "You need information. Ask about vegan food options.", "Learner asked about vegan items.", scene_hint="A glass display case shows fresh pastries labeled with small wooden signboards."),
    Task("Ask for a receipt", "You need something. Request your receipt.", "Learner asked for a receipt.", phase=3),
    Task("Order an iced latte", "You want to buy this. Order an iced latte.", "Learner ordered an iced latte.", phase=1, scene_hint="Condensation drips down a clear plastic cup filled with ice cubes on the pick-up counter."),
    Task("Use the word 'decaf'", "Decaf refers to coffee beans or drinks that have had almost all caffeine removed. Ask for a decaf espresso.", "Learner used the word 'decaf'."),
    Task("Complain that the coffee is too cold", "You need to communicate this. Say your coffee is cold.", "Learner complained about cold coffee.", reactive=True, scene_hint="Steam has stopped rising from your mug, and the coffee surface feels lukewarm."),
    Task("Ask for the wifi password", "You need information. Ask for the wifi password.", "Learner asked for the wifi password."),
    Task("Ask what time they close", "You need information. Ask about closing time.", "Learner asked what time the shop closes.", phase=3),
    Task("Order a blueberry muffin", "You want to buy this. Order a muffin.", "Learner ordered a blueberry muffin.", scene_hint="Warm blueberry pastries sit under a glass dome on the counter, dusted with sugar."),
    Task("Say you have a loyalty card", "This is important context. Mention your loyalty or stamp card.", "Learner mentioned a loyalty card.", phase=3),
    Task("Ask if you can pay with cash", "You need information. Ask to pay in cash.", "Learner asked to pay with cash.", phase=3),
    Task("Use the word 'artisan'", "Artisan describes food or drink crafted in small batches using traditional, non-automated methods. Inquire if the pastries come from a local artisan bakery.", "Learner used the word 'artisan'."),
    Task("Ask for extra sugar", "You need information. Ask for more sugar.", "Learner asked for extra sugar."),
    Task("Ask for skim milk", "You need information. Ask for skim milk.", "Learner requested skim milk."),
    Task("Ask if there are any seasonal drinks", "You need information. Ask about seasonal or special drinks.", "Learner asked about seasonal specials.", phase=1),
    Task("Say your friend is coming to pay", "You need to communicate this. Say you are waiting for a friend to pay.", "Learner mentioned a friend will pay.", phase=3),
    Task("Ask for a cup holder", "You need information. Ask for a sleeve or cup holder.", "Learner asked for a cup holder or sleeve.", scene_hint="Cardboard cup sleeves sit in a tall wire dispenser beside the napkin box."),
    Task("Ask if the beans are locally sourced", "You need information. Ask where the coffee beans are from.", "Learner asked about the origin of the beans."),
    Task("Order a hot chocolate", "You want to buy this. Order a hot chocolate.", "Learner ordered a hot chocolate."),
    Task("Say the music is too loud", "You have a delicate request. Politely ask them to turn down the music.", "Learner complained about loud music.", scene_hint="music is playing over the shop's speakers, and it's turned up high — upbeat and loud enough to talk over."),
    Task("Ask for a glass of tap water", "You need information. Ask for tap water.", "Learner requested tap water."),
    Task("Use the word 'recommendation'", "A recommendation is a suggestion regarding the best option to choose. Ask the barista for a specialty drink recommendation.", "Learner used the word 'recommendation'."),
    Task("Ask if the pastries are fresh today", "You need information. Ask if the food is fresh.", "Learner asked if pastries were baked today."),
    Task("Say you have an allergy to nuts", "This is important context. Mention a nut allergy.", "Learner mentioned a nut allergy."),
    Task("Ask for a larger cup but same amount of coffee", "You need information. Ask for room for milk.", "Learner asked for room for milk/larger cup."),
    Task("Leave a tip", "You need to communicate this. Say you are leaving a tip.", "Learner explicitly mentioned giving a tip.", phase=3),
    Task("Ask how long the wait is", "You need information. Ask about the wait time.", "Learner asked how long the order will take."),
    Task("Ask for a paper straw", "You need information. Ask for a straw.", "Learner asked for a paper straw.", scene_hint="A jar of colorful paper straws stands next to the wooden stirring sticks on the pick-up counter."),
    Task("Say you accidentally spilled your drink", "You made a mistake. Apologize for spilling.", "Learner mentioned spilling their drink.", reactive=True),
    Task("Ask for a replacement drink", "You need information. Ask for a new drink.", "Learner asked for a replacement.", reactive=True),
    Task("Use the word 'flavor'", "Flavor refers to the distinctive taste and aroma profile of a beverage or food item. Inquire about available syrup flavors.", "Learner used the word 'flavor'."),
    Task("Ask if you can sit anywhere", "You need information. Ask about seating.", "Learner asked if seating is open/free.", phase=1),
    Task("Say the table is dirty", "You noticed a problem. Point out a dirty table.", "Learner mentioned a dirty table.", scene_hint="the shop is slammed, and used cups and crumbs are piling up on the tables because no one has had a chance to clear them yet."),
    Task("Order two espressos", "You want to buy this. Order two shots of espresso.", "Learner ordered two espressos.", phase=1, scene_hint="Two small ceramic espresso cups sit steaming on a brass counter tray."),
    Task("Ask if they sell whole beans", "You need information. Ask to buy coffee bags/beans.", "Learner asked about buying whole beans.", scene_hint="Bags of roasted coffee beans with brown parchment labels are displayed on wooden wall shelves."),
    Task("Use the word 'caffeine'", "Caffeine is a natural stimulant found in coffee and tea that increases alertness. Inquire about the caffeine content of the cold brew.", "Learner used the word 'caffeine'."),
    Task("Say you want the drink extra hot", "You need information. Ask for the drink to be very hot.", "Learner asked for an extra hot drink.", reactive=True, scene_hint="The barista stretches milk with the steam wand, creating a loud high-pitched hiss."),
    Task("Ask if they do a student discount", "You need information. Ask about discounts.", "Learner asked about a student discount.", phase=3, reactive=True),
    Task("Say 'keep the change'", "You must inform them. Tell them to keep the change.", "Learner told the cashier to keep the change.", phase=3, reactive=True),
    Task("Ask for a wooden stirrer", "You need information. Ask for a stirrer.", "Learner asked for a stirrer."),
    Task("Say thank you and goodbye", "You need to communicate this. Say goodbye.", "Learner thanked the staff and said goodbye.", phase=3),
    Task("Turn down their recommendation and explain why", "They've suggested something. Say no politely, and give a real reason.", "Learner declined the suggestion AND gave a reason for declining.", difficulty="advanced", reactive=True),
    Task("Weigh up two drinks, then pick one", "Mention both options, say what makes them different, and commit to one.", "Learner referred to two options AND stated a preference with a justification.", difficulty="advanced"),
    Task("Point out a problem with your order without being rude", "Something isn't right. Raise it politely and say what you'd like done.", "Learner raised a problem AND requested or proposed a resolution, using polite or softening language.", difficulty="advanced", reactive=True),
    Task("Say you didn't catch that and ask them to repeat", "You missed something. Ask them to say it again, and be specific about which part.", "Learner signalled they didn't understand AND specified what they need repeated or explained.", difficulty="advanced"),
    Task("Explain that you're in a hurry without sounding rude", "You have ten minutes. Communicate the pressure and find out what's quickest.", "Learner conveyed time pressure AND asked for a faster option or for reassurance about timing.", difficulty="advanced", reactive=True),
    Task("Guess what an unfamiliar item is, then check", "You don't know what it is. Say what you think it might be, then ask.", "Learner used hedging language such as might, probably, I think, or sounds like AND asked a follow-up question.", difficulty="advanced"),
    Task("Ask for the drink to be made differently", "You want a change to the standard version. Ask, and say what to do if it isn't possible.", "Learner requested a modification AND offered a fallback or asked what is possible.", difficulty="advanced", reactive=True),
    Task("Politely disagree with something they said", "You see it differently. Say so without being blunt, and back it up.", "Learner expressed disagreement using softening language AND supported it with a reason.", difficulty="advanced"),
    Task("Keep the small talk going", "They've made a casual remark. Answer it and give them something back.", "Learner responded to the remark AND added a related comment or question of their own.", difficulty="advanced"),
    Task("Negotiate when your order isn't available", "The size or drink you want is out of stock. Weigh it against an alternative, and commit to one.", "Learner acknowledged the unavailability AND compared it to an alternative AND committed to a substitute with a reason.", difficulty="advanced", reactive=True),
    Task("Dispute a billing mistake", "You were charged for something you didn't order. Point out exactly what's wrong, and ask for it to be corrected.", "Learner identified the specific billing error AND requested a correction, without being accusatory.", difficulty="advanced", phase=3),
    Task("Escalate after the first fix wasn't enough", "Your first request for a fix wasn't sufficient. Push back and explain why the first offer doesn't solve it.", "Learner acknowledged the initial response AND explained why it was insufficient AND asked for a further remedy.", difficulty="advanced", reactive=True),
    Task("Persuade them to make an off-menu request", "Ask for a modification that isn't standard. Explain exactly what you want and why it matters to you.", "Learner requested a specific non-standard modification AND gave a reason for wanting it.", difficulty="advanced"),
    Task("Raise a hypothetical about running late", "Ask what would happen if you had to leave before your order is ready — held, remade, or refunded?", "Learner posed a hypothetical about being unable to wait AND asked what the barista would do about it.", difficulty="advanced"),
    Task("Negotiate a loyalty discount", "Ask if there's a discount or loyalty perk available, and give a reason you think you qualify.", "Learner asked about a discount or perk AND gave a justification for requesting it.", difficulty="advanced"),
    Task("Push back diplomatically after tasting your drink", "Something you already received doesn't taste right. Say so tactfully, and ask specifically what they can do about it.", "Learner raised a specific quality issue with the drink they received AND requested a specific remedy.", difficulty="advanced", reactive=True),
    Task("Weigh a health trade-off out loud", "You're deciding between two drinks for a specific reason (caffeine, sugar, etc). Explain the trade-off and ask for their opinion.", "Learner explained a personal constraint relevant to the choice AND asked for the barista's recommendation based on it.", difficulty="advanced"),
    Task("Clarify a mismatched order", "What arrived isn't quite what you asked for. Explain the mismatch precisely and propose how to fix it.", "Learner pinpointed the specific mismatch between what was ordered and what was received AND proposed a fix.", difficulty="advanced", reactive=True),
    Task("Question whether it's worth the price", "Ask where the beans/ingredients come from, then follow up connecting that to whether it's worth the price.", "Learner asked about the origin or quality of the product AND followed up connecting it to value or price.", difficulty="advanced")
]