scenario_4_tasks = [
    Task("Say you have a reservation", "You need to communicate this. Say you want to check in.", "Learner stated they have a reservation.", phase=1, scene_hint="Soft jazz plays quietly in the grand hotel lobby as guests move past decorative palm trees."),
    Task("Spell your last name", "They need precise details. Spell out your name.", "Learner spelled their name.", phase=1),
    Task("Provide your passport", "You need to communicate this. Say here is my passport.", "Learner offered their ID or passport.", phase=1),
    Task("Ask for a quiet room", "You need information. Ask for a room away from the elevator.", "Learner asked for a quiet room.", phase=1),
    Task("Use the word 'upgrade'", "An upgrade is an improvement or promotion to a higher category of accommodation. Ask if a complimentary room upgrade is available.", "Learner used the word 'upgrade'.", phase=1),
    Task("Ask what time breakfast is", "You need information. Ask about breakfast hours.", "Learner asked about breakfast times."),
    Task("Ask where the breakfast room is", "You need information. Ask for directions to breakfast.", "Learner asked where breakfast is served."),
    Task("Ask for the wifi password", "You need information. Ask for internet access.", "Learner asked for the wifi password."),
    Task("Ask what time checkout is", "You need information. Ask about checkout time.", "Learner asked when they must check out."),
    Task("Request a late checkout", "You need information. Ask to leave at 1 PM.", "Learner requested a late checkout.", difficulty="advanced"),
    Task("Use the word 'deposit'", "A deposit is a sum paid as security for potential incidental charges during a hotel stay. Inquire about the security deposit requirement.", "Learner used the word 'deposit'.", reactive=True),
    Task("Say the AC in your room is broken", "You are not satisfied. Complain about the air conditioning.", "Learner mentioned broken AC.", reactive=True, scene_hint="The air conditioning unit in the room emits a loud metallic rattling noise without cooling."),
    Task("Ask for a different room", "You need something. Request to change rooms.", "Learner asked for a room change.", difficulty="advanced", reactive=True),
    Task("Ask for an extra key card", "You need information. Ask for another room key.", "Learner asked for an extra key."),
    Task("Ask for a wake-up call", "You need something. Request a wake-up call for 7 AM.", "Learner requested a wake-up call."),
    Task("Use the word 'luggage'", "Luggage refers to bags, suitcases, and trunks containing personal belongings. Ask whether the front desk can store your luggage.", "Learner used the word 'luggage'.", scene_hint="Several large leather suitcases with brass baggage tags are stacked neatly on a bellhop trolley."),
    Task("Ask for extra towels", "You need something. Request more towels.", "Learner asked for extra towels.", reactive=True),
    Task("Ask where the gym is", "You need information. Ask for the fitness center.", "Learner asked for the gym."),
    Task("Ask if the pool is heated", "You need information. Ask about the swimming pool.", "Learner asked if the pool is heated.", scene_hint="A lit blue swimming pool surrounded by lounge chairs is visible through glass doors."),
    Task("Ask if breakfast is included in the room rate", "You need information. Ask if breakfast is included.", "Learner asked if breakfast is included."),
    Task("Ask for a city map", "You need information. Ask if they have a map.", "Learner asked for a map."),
    Task("Ask for a restaurant recommendation", "You need information. Ask for a good local place to eat.", "Learner asked for a restaurant recommendation."),
    Task("Ask them to book a taxi", "You need something. Request a taxi for tomorrow.", "Learner asked the hotel to book a taxi."),
    Task("Use the word 'vicinity'", "Vicinity refers to the surrounding area, neighborhood, or proximity of a place. Ask about fine dining options in the hotel's immediate vicinity.", "Learner used the word 'vicinity'.", phase=2),
    Task("Say you lost your room key", "Report a lost key.", "Learner said they lost their key.", reactive=True, scene_hint="An out-of-order tag hangs on the elevator door in the main hallway."),
    Task("Ask for an adapter", "You need information. Ask for a power adapter.", "Learner asked for a plug adapter.", reactive=True),
    Task("Say the room is too noisy", "You are not satisfied. Complain about noise.", "Learner complained about noise.", reactive=True, scene_hint="Construction drilling echoes loudly from the adjacent hotel wing."),
    Task("Ask for room service", "You need information. Ask how to order food to the room.", "Learner asked about room service."),
    Task("Use the word 'housekeeping'", "Housekeeping is the hotel department responsible for cleaning and maintaining guest rooms. Request housekeeping to refresh your room.", "Learner used the word 'housekeeping'.", reactive=True),
    Task("Ask if there is a laundry service", "You need information. Ask about washing clothes.", "Learner asked about laundry service."),
    Task("Say you didn't take anything from the minibar", "There is a misunderstanding. Deny minibar charges.", "Learner said they didn't use the minibar.", phase=3),
    Task("Ask for an iron", "You need information. Ask for an ironing board.", "Learner asked for an iron."),
    Task("Ask housekeeping for an extra blanket", "You need information. Ask for an extra blanket.", "Learner asked for an extra blanket."),
    Task("Ask if tap water is safe to drink", "You need information. Ask about drinking water.", "Learner asked if tap water is safe."),
    Task("Say your TV isn't working", "Report a broken TV.", "Learner reported the TV is broken.", reactive=True, scene_hint="The wall-mounted television screen displays static noise when turned on."),
    Task("Ask to speak to the manager", "You need something. Request the manager.", "Learner asked for the manager.", difficulty="advanced"),
    Task("Ask for the nearest subway station", "You need information. Ask for transport directions.", "Learner asked for the subway/train station."),
    Task("Ask for a printed itemized receipt", "You need information. Ask for a final receipt.", "Learner asked for a final receipt.", phase=3),
    Task("Ask if you can pay with two different cards", "You have a payment preference. Split the payment.", "Learner asked to split payment on cards.", phase=3),
    Task("Say you enjoyed your stay", "You want to show appreciation. Give a compliment.", "Learner said they had a good stay.", phase=3),
    Task("Ask for a double bed instead of two singles", "You need something. Request a different bed type.", "Learner requested a double/king bed.", difficulty="advanced"),
    Task("Ask for a room with an ocean view", "You need information. Ask for a room with a nice view.", "Learner asked for a room with a view."),
    Task("Say you are checking out early", "This is important context. Mention an early departure.", "Learner mentioned leaving early.", phase=3),
    Task("Ask if there is a shuttle bus", "You need information. Ask about the airport shuttle.", "Learner asked about a shuttle bus."),
    Task("Say the bathroom has no soap", "You are not satisfied. Complain about missing amenities.", "Learner mentioned missing soap.", reactive=True, scene_hint="A brass soap dish on the bathroom sink is empty."),
    Task("Ask for a smoking area", "You need information. Ask where you can smoke.", "Learner asked for a smoking area."),
    Task("Ask if pets are allowed", "You need information. Ask about bringing a dog.", "Learner asked about pet policy."),
    Task("Ask the front desk to confirm your departure date", "You need information. Ask them to confirm your departure date.", "Learner asked to confirm departure date."),
    Task("Thank the receptionist", "You need to communicate this. Say thanks and bye.", "Learner thanked the receptionist.", phase=3),
    Task("Report a problem with the room and say what you'd like done", "Describe the issue clearly, then make a specific request.", "Learner described a problem AND made a specific request about how to resolve it.", difficulty="advanced", reactive=True),
    Task("Ask to check out later and give a reason", "You need extra time. Explain why and ask whether it's possible.", "Learner requested a later checkout AND gave a reason for needing it.", difficulty="advanced"),
    Task("Compare the two rooms they offer and choose", "Ask about the difference, weigh it up out loud, then decide.", "Learner referred to both options AND chose one with a justification.", difficulty="advanced"),
    Task("Ask for directions, then repeat them back", "Get the directions, then confirm you've understood by saying them again.", "Learner asked for directions AND restated them to confirm.", difficulty="advanced"),
    Task("Raise a discrepancy with your booking calmly", "Something doesn't match what you booked. Point it out politely and ask how to sort it.", "Learner identified a discrepancy AND asked how it can be resolved, without accusatory language.", difficulty="advanced"),
    Task("Decline the upgrade they're offering", "Say no to the upsell, politely, with a reason.", "Learner declined the offer AND gave a reason.", difficulty="advanced"),
    Task("Negotiate an early check-in with a fallback", "You arrived early and your room isn't ready. Explain why it matters, and negotiate an alternative like luggage storage.", "Learner explained why early check-in matters to them AND negotiated a concrete alternative.", difficulty="advanced"),
    Task("Dispute a billing discrepancy with specifics", "The final bill doesn't match what you were quoted. Point out exactly which charge is wrong and ask for it to be corrected.", "Learner identified the specific incorrect charge AND asked for a correction or explanation.", difficulty="advanced", phase=3),
    Task("Escalate after the first fix wasn't sufficient", "The first solution they offered doesn't fully solve your problem. Explain why, and ask for something more.", "Learner explained why the initial resolution was insufficient AND requested a further remedy.", difficulty="advanced", reactive=True),
    Task("Negotiate a special room request with a fallback", "You need something specific (quiet room, high floor) for a real reason. Explain why, and ask what to do if it's not available.", "Learner explained the reason for the request AND asked for a fallback option if unavailable.", difficulty="advanced"),
    Task("Demand a concrete resolution to a noise complaint", "It was too loud to sleep. Describe the problem specifically and ask for both an apology and a concrete fix.", "Learner described the noise problem specifically AND requested a concrete resolution.", difficulty="advanced", reactive=True, scene_hint="Heavy bass music vibrates through the wall from an event in the adjacent ballroom."),
    Task("Push back on being charged for something unused", "You're being billed for a service or amenity you never used. Point it out and ask for it to be removed.", "Learner identified the specific unused charge AND requested its removal.", difficulty="advanced", phase=3),
    Task("Reason through a cancellation policy hypothetically", "Ask what happens if you need to leave a day early, and reason out loud about whether it's worth it given any fee.", "Learner asked about the cancellation or early-departure policy AND reasoned about whether it's worth it given the cost.", difficulty="advanced", phase=3),
    Task("Negotiate luggage storage around an inconvenient schedule", "Your flight is much later than checkout. Explain the gap and negotiate a solution for your bags and your time.", "Learner explained the scheduling gap AND negotiated a specific solution.", difficulty="advanced"),
    Task("Contest a mismatch with your original booking", "What you're being offered doesn't match your original booking confirmation. Point out the exact mismatch and ask for it to be honored.", "Learner identified the specific mismatch with the original booking AND asked for it to be honored or corrected.", difficulty="advanced", reactive=True),
    Task("Compare a same-tier alternative and decide", "Your exact room type isn't available. Ask what's comparable, weigh it against your original request, and decide.", "Learner asked for a comparable alternative AND compared it against the original request AND made a decision.", difficulty="advanced", reactive=True, scene_hint="The receptionist types into a terminal behind a polished marble front desk."),
    Task('Request additional clothing hangers for your room closet', 'Ask front desk to send up extra coat hangers.', 'Learner requested extra clothing hangers for the room closet.', phase=1, scene_hint='A framed floorplan of guest rooms and suites hangs on the wall behind the desk.'),
    Task("Speak to the receptionist about your room requirements.", "Begin by mentioning any specific room preferences or needs you may have, such as a view or extra bedding.", "Learner expresses their specific room preferences to the receptionist.", phase=1, scene_hint="Glossy brochures depicting the hotel pool, spa, and restaurant sit in a counter display."),
    Task("Ask about the hotel amenities.", "Inquire about what amenities are available at the hotel, such as a gym, spa, or swimming pool.", "Learner asks the receptionist about the hotel's amenities.", phase=1, scene_hint="Two electronic key cards with gold foil hotel logos lie on the marble counter."),
    Task("Request a key to your room.", "politely ask the receptionist for your room key, confirming the room number or reservation number if needed.", "Learner asks the receptionist for a key to their room.", phase=3)
]